### ISSUE TITLE
Release v1.0.0-alpha.9

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO-TraitGen#74]
Release the latest changes, and update downstream dependents (esp. MediaCreation).
```[tasklist]
### Tasks
- [x] Release TraitGen
- [x] Release MediaCreation
- [x] Update integrations.yml
- [ ] Update BAL
- [x] Check unpinned downstream projects (e.g. usdOpenAssetIOResolver)
```

**Comment by elliotcmorris** [comment]
Integrations.yml is tested via test-cmake, wihch pulls in the latest version of mediacreation as a submodule against main, so that's fine.

As for BAL ... I think updating that might be bad practice. This is purely a host side update, so bumping a greater than dependency seems to needlessly introduce incompatibility, it's better to remain supporting >= alpha 7 imo, under the principle of maximum compatibiliy

For that reason, closing this, feel free to reopen if you disagree.
